version: '3.8'

services:
  genshin_god_field:
    build: .
    container_name: genshin_god_field
    restart: always
    # 關鍵：將主機的 65432 對接到容器的 65432
    ports:
      - "65432:65432"
    # 如果有用到環境變數（例如 DB 密碼），可以加在這裡
    # env_file: .env